server:
  port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost/dssdb?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: '*#m@RC0s$%'
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
              ddl-auto: update
              show_sql: true
              use_sql_comments: true
              format_sql: true
              open-in-view: true
              dialect: org.hibernate.dialect.MySQL5InnoDBDialect